name: flutter_login
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
